services:
  php:
    build:
      context: ./
      dockerfile: php82.dockerfile
    env_file:
      .env
    volumes:
      - ./src:/usr/local/opnsense
      - ./config.xml.sample:/conf/config.xml
      - ./configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint:
      sh -c "chown -R www-data:www-data /usr/local/opnsense/mvc/app/cache && php-fpm"
  nginx:
    image: library/nginx:alpine
    environment:
      - NGINX_DOMAIN=${NGINX_DOMAIN}
      - NGINX_PHP_HOST=${NGINX_PHP_HOST}
    ports:
      - "8001:80"
    volumes:
      - ./src:/usr/local/opnsense
      - ./configs/nginx.conf:/etc/nginx/templates/site.conf.template
    depends_on:
      - php